// default package
// Generated 28 dic 2024, 23:36:21 by Hibernate Tools 4.3.6.Final
package com.dani.springjokesmvc.models.entities;

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

/**
 * Flags generated by hbm2java
 */
@Entity
@Table(name = "flags")
public class Flags implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "flag_seq")
	@SequenceGenerator(name = "flag_seq", sequenceName = "seq_flags", allocationSize = 1)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	@Column(name = "flag", nullable = false)
	private String flag;
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "jokes_flags", joinColumns = {
			@JoinColumn(name = "flag_id", referencedColumnName="id") }, inverseJoinColumns = {
					@JoinColumn(name = "joke_id", referencedColumnName="id") })
	@JsonIgnoreProperties("flagses")
	private Set<Jokes> jokeses = new HashSet<Jokes>(0);
	
	/*
	@Column(name="create_at")
	@Temporal(TemporalType.DATE)
	private LocalDate createAt;
*/
	public Flags() {
	}
	
	public Flags(String flag) {
		this.flag = flag;
	}

	public Flags(int id, String flag) {
		this.id = id;
		this.flag = flag;
	}

	public Flags(int id, String flag, Set<Jokes> jokeses) {
		this.id = id;
		this.flag = flag;
		this.jokeses = jokeses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Set<Jokes> getJokeses() {
		return this.jokeses;
	}

	public void setJokeses(Set<Jokes> jokeses) {
		this.jokeses = jokeses;
	}
	
	public String toString() {
		return id + " | " + flag;
	}
}
